package chunk108

import (
	"errors"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// ============================================================
// Constants
// ============================================================

const (
	// DefaultMaxPids_108 is the default maximum number of pids allowed.
	DefaultMaxPids_108 int64 = 65536

	// DefaultWarnPercent_108 is the default warning threshold percentage.
	DefaultWarnPercent_108 = 80

	// MinWarnPercent_108 is the minimum allowed warning percentage.
	MinWarnPercent_108 = 1

	// MaxWarnPercent_108 is the maximum allowed warning percentage.
	MaxWarnPercent_108 = 100

	// HardMaxPids_108 is the absolute maximum pids value (kernel limit).
	HardMaxPids_108 int64 = 4194304

	// MinMaxPids_108 is the minimum valid pids max value.
	MinMaxPids_108 int64 = 1

	// MaxPidsUnlimited_108 is the string representation for unlimited.
	MaxPidsUnlimited_108 = "max"

	// WarningNone_108 indicates no warning.
	WarningNone_108 WarningLevel_108 = iota

	// WarningLow_108 indicates low warning severity.
	WarningLow_108

	// WarningMedium_108 indicates medium warning severity.
	WarningMedium_108

	// WarningHigh_108 indicates high warning severity.
	WarningHigh_108

	// WarningCritical_108 indicates critical warning severity.
	WarningCritical_108
)

// ============================================================
// Error variables
// ============================================================

var (
	ErrInvalidMaxPids_108       = errors.New("invalid pids.max value: must be positive integer or 'max'")
	ErrNegativeLimit_108        = errors.New("pids.max cannot be negative")
	ErrExceedsHardLimit_108     = fmt.Errorf("pids.max exceeds hard limit of %d", HardMaxPids_108)
	ErrInvalidWarnPercent_108   = fmt.Errorf("warning percentage must be between %d and %d", MinWarnPercent_108, MaxWarnPercent_108)
	ErrPolicyNil_108            = errors.New("policy pointer is nil")
	ErrUsageNil_108             = errors.New("usage pointer is nil")
	ErrCurrentExceedsMax_108    = errors.New("current pids usage exceeds max")
	ErrNegativeCurrent_108      = errors.New("current pids usage cannot be negative")
	ErrDuplicateEntry_108       = errors.New("duplicate threshold entry")
	ErrThresholdOutOfOrder_108  = errors.New("threshold entries must be in increasing order of min percent")
)

// ============================================================
// Types
// ============================================================

// WarningLevel_108 defines the severity level of a pids warning.
type WarningLevel_108 int

// String returns the string representation of the warning level.
func (w WarningLevel_108) String_108() string {
	switch w {
	case WarningNone_108:
		return "none"
	case WarningLow_108:
		return "low"
	case WarningMedium_108:
		return "medium"
	case WarningHigh_108:
		return "high"
	case WarningCritical_108:
		return "critical"
	default:
		return fmt.Sprintf("unknown(%d)", int(w))
	}
}

// PidsMaxPolicy_108 defines the policy for near-limit warnings.
type PidsMaxPolicy_108 struct {
	// Max is the maximum number of pids allowed.
	Max int64

	// WarnPercent is the usage percentage at which warnings begin.
	WarnPercent int

	// WarnThreshold is the absolute value at which warnings trigger (computed).
	WarnThreshold int64

	// PolicyName is an optional human-readable name for the policy.
	PolicyName string

	// EnableWarnings enables or disables warning generation.
	EnableWarnings bool
}

// PidsUsage_108 holds the current and maximum pids usage data.
type PidsUsage_108 struct {
	// Current is the current number of pids used.
	Current int64

	// Max is the maximum number of pids allowed (same as policy.Max).
	Max int64

	// Timestamp is an optional Unix timestamp of the usage snapshot.
	Timestamp int64
}

// ThresholdEntry_108 defines a single threshold in a table.
type ThresholdEntry_108 struct {
	// Level is the warning level for this threshold.
	Level WarningLevel_108

	// MinPercent is the lower bound percentage (inclusive).
	MinPercent int

	// MaxPercent is the upper bound percentage (exclusive, unless 100).
	MaxPercent int

	// Action is a recommended action string.
	Action string
}

// WarningEvent_108 represents a warning event generated by the policy.
type WarningEvent_108 struct {
	// Level is the severity level.
	Level WarningLevel_108

	// Message is a human-readable warning message.
	Message string

	// Timestamp is the Unix timestamp when the event was generated.
	Timestamp int64

	// PolicyName is the name of the policy that generated the event.
	PolicyName string
}

// ============================================================
// Default Threshold Table
// ============================================================

// DefaultThresholdTable_108 is the default table of thresholds.
var DefaultThresholdTable_108 = []ThresholdEntry_108{
	{Level: WarningNone_108, MinPercent: 0, MaxPercent: 50, Action: "No action needed"},
	{Level: WarningLow_108, MinPercent: 50, MaxPercent: 70, Action: "Monitor pids usage; consider scaling"},
	{Level: WarningMedium_108, MinPercent: 70, MaxPercent: 85, Action: "Increase pids.max or reduce processes"},
	{Level: WarningHigh_108, MinPercent: 85, MaxPercent: 95, Action: "Immediate action required: check runaway processes"},
	{Level: WarningCritical_108, MinPercent: 95, MaxPercent: 100, Action: "Critical: pids exhaustion imminent"},
}

// ============================================================
// Constructor Functions
// ============================================================

// NewPidsMaxPolicy_108 creates a new policy with the given max and warn percent.
// Returns an error if parameters are invalid.
func NewPidsMaxPolicy_108(max int64, warnPercent int, name string) (*PidsMaxPolicy_108, error) {
	if err := ValidatePidsMax_108(max); err != nil {
		return nil, err
	}
	if warnPercent < MinWarnPercent_108 || warnPercent > MaxWarnPercent_108 {
		return nil, ErrInvalidWarnPercent_108
	}
	policy := &PidsMaxPolicy_108{
		Max:            max,
		WarnPercent:    warnPercent,
		WarnThreshold:  calculateWarnThreshold_108(max, warnPercent),
		PolicyName:     name,
		EnableWarnings: true,
	}
	return policy, nil
}

// DefaultPolicy_108 creates a policy with default values.
func DefaultPolicy_108() *PidsMaxPolicy_108 {
	p, _ := NewPidsMaxPolicy_108(DefaultMaxPids_108, DefaultWarnPercent_108, "default")
	return p
}

// NewPidsUsage_108 creates a new usage snapshot.
func NewPidsUsage_108(current, max int64, timestamp int64) *PidsUsage_108 {
	return &PidsUsage_108{
		Current:   current,
		Max:       max,
		Timestamp: timestamp,
	}
}

// ============================================================
// Validation Functions
// ============================================================

// ValidatePidsMax_108 checks that the limit is valid.
func ValidatePidsMax_108(limit int64) error {
	if limit < 0 {
		return ErrNegativeLimit_108
	}
	if limit == 0 {
		return ErrInvalidMaxPids_108
	}
	if limit > HardMaxPids_108 {
		return ErrExceedsHardLimit_108
	}
	return nil
}

// ValidatePolicy_108 performs full validation of a policy.
func ValidatePolicy_108(policy *PidsMaxPolicy_108) error {
	if policy == nil {
		return ErrPolicyNil_108
	}
	if err := ValidatePidsMax_108(policy.Max); err != nil {
		return err
	}
	if policy.WarnPercent < MinWarnPercent_108 || policy.WarnPercent > MaxWarnPercent_108 {
		return ErrInvalidWarnPercent_108
	}
	return nil
}

// ValidateUsage_108 checks that usage is valid.
func ValidateUsage_108(usage *PidsUsage_108) error {
	if usage == nil {
		return ErrUsageNil_108
	}
	if usage.Current < 0 {
		return ErrNegativeCurrent_108
	}
	if usage.Max > 0 && usage.Current > usage.Max {
		return ErrCurrentExceedsMax_108
	}
	return nil
}

// ValidateThresholdTable_108 validates a threshold table.
func ValidateThresholdTable_108(table []ThresholdEntry_108) error {
	if len(table) == 0 {
		return errors.New("threshold table cannot be empty")
	}
	seen := make(map[WarningLevel_108]bool)
	prevMax := 0
	for i, entry := range table {
		if entry.MinPercent < 0 || entry.MaxPercent > 100 || entry.MinPercent >= entry.MaxPercent {
			return fmt.Errorf("entry %d: invalid percent range [%d, %d)", i, entry.MinPercent, entry.MaxPercent)
		}
		if entry.MinPercent != prevMax {
			return ErrThresholdOutOfOrder_108
		}
		if seen[entry.Level] {
			return ErrDuplicateEntry_108
		}
		seen[entry.Level] = true
		prevMax = entry.MaxPercent
	}
	if prevMax != 100 {
		return errors.New("threshold table must cover 0-100%")
	}
	return nil
}

// ============================================================
// Parsing / Formatting
// ============================================================

// ParsePidsMax_108 parses a string into a max value.
// Accepts "max" (unlimited) or a positive integer.
func ParsePidsMax_108(s string) (int64, error) {
	s = strings.TrimSpace(s)
	if strings.EqualFold(s, MaxPidsUnlimited_108) {
		return math.MaxInt64, nil
	}
	val, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%w: %s", ErrInvalidMaxPids_108, s)
	}
	if val < 0 {
		return 0, ErrNegativeLimit_108
	}
	return val, nil
}

// FormatPidsMax_108 formats a max value as a string.
// Uses "max" for math.MaxInt64, otherwise decimal.
func FormatPidsMax_108(max int64) string {
	if max == math.MaxInt64 {
		return MaxPidsUnlimited_108
	}
	return strconv.FormatInt(max, 10)
}

// FormatUsagePercent_108 formats a usage percentage to one decimal place.
func FormatUsagePercent_108(percent float64) string {
	return fmt.Sprintf("%.1f%%", percent)
}

// ============================================================
// Computation Helpers
// ============================================================

// calculateWarnThreshold_108 computes the absolute threshold from max and warnPercent.
func calculateWarnThreshold_108(max int64, warnPercent int) int64 {
	if max <= 0 {
		return 0
	}
	threshold := int64(math.Ceil(float64(max) * float64(warnPercent) / 100.0))
	if threshold > max {
		threshold = max
	}
	return threshold
}

// ComputeUsagePercent_108 returns the usage percentage as a float64 (0-100).
func ComputeUsagePercent_108(current, max int64) float64 {
	if max <= 0 {
		return 0.0
	}
	if current >= max {
		return 100.0
	}
	return float64(current) * 100.0 / float64(max)
}

// IsNearLimit_108 checks if usage is at or above the warning threshold.
func IsNearLimit_108(policy *PidsMaxPolicy_108, usage *PidsUsage_108) bool {
	if policy == nil || usage == nil {
		return false
	}
	if !policy.EnableWarnings {
		return false
	}
	if policy.WarnThreshold <= 0 {
		return false
	}
	return usage.Current >= policy.WarnThreshold
}

// ============================================================
// Warning Level Determination
// ============================================================

// GetWarningLevel_108 returns the warning level for a given usage percentage.
func GetWarningLevel_108(percent float64, table []ThresholdEntry_108) WarningLevel_108 {
	if len(table) == 0 {
		table = DefaultThresholdTable_108
	}
	for _, entry := range table {
		if percent >= float64(entry.MinPercent) && percent < float64(entry.MaxPercent) {
			return entry.Level
		}
	}
	// Exactly 100% -> last entry (critical)
	if percent >= 100.0 {
		return WarningCritical_108
	}
	return WarningNone_108
}

// GetWarningLevelFromUsage_108 is a convenience function.
func GetWarningLevelFromUsage_108(usage *PidsUsage_108) WarningLevel_108 {
	percent := ComputeUsagePercent_108(usage.Current, usage.Max)
	return GetWarningLevel_108(percent, DefaultThresholdTable_108)
}

// ============================================================
// Warning and Policy Application
// ============================================================

// CheckWarning_108 evaluates usage against policy and returns warning level and message.
func CheckWarning_108(policy *PidsMaxPolicy_108, usage *PidsUsage_108) (WarningLevel_108, string) {
	if err := ValidatePolicy_108(policy); err != nil {
		return WarningNone_108, fmt.Sprintf("invalid policy: %v", err)
	}
	if err := ValidateUsage_108(usage); err != nil {
		return WarningNone_108, fmt.Sprintf("invalid usage: %v", err)
	}
	if !policy.EnableWarnings {
		return WarningNone_108, "warnings disabled"
	}
	percent := ComputeUsagePercent_108(usage.Current, usage.Max)
	level := GetWarningLevel_108(percent, DefaultThresholdTable_108)
	msg := fmt.Sprintf("PIDs usage at %s (current=%d, max=%d, policy=%s)",
		FormatUsagePercent_108(percent), usage.Current, usage.Max, policy.PolicyName)
	return level, msg
}

// ApplyPolicy_108 applies the policy to the usage and returns a warning event if warranted.
func ApplyPolicy_108(policy *PidsMaxPolicy_108, usage *PidsUsage_108) *WarningEvent_108 {
	level, msg := CheckWarning_108(policy, usage)
	if level == WarningNone_108 {
		return nil
	}
	return &WarningEvent_108{
		Level:      level,
		Message:    msg,
		Timestamp:  usage.Timestamp,
		PolicyName: policy.PolicyName,
	}
}

// ============================================================
// Policy Mutators
// ============================================================

// SetMax_108 updates the max value and recalculates threshold.
func SetMax_108(policy *PidsMaxPolicy_108, newMax int64) error {
	if err := ValidatePidsMax_108(newMax); err != nil {
		return err
	}
	policy.Max = newMax
	policy.WarnThreshold = calculateWarnThreshold_108(policy.Max, policy.WarnPercent)
	return nil
}

// SetWarnPercent_108 updates the warning percent and recalculates threshold.
func SetWarnPercent_108(policy *PidsMaxPolicy_108, newPercent int) error {
	if newPercent < MinWarnPercent_108 || newPercent > MaxWarnPercent_108 {
		return ErrInvalidWarnPercent_108
	}
	policy.WarnPercent = newPercent
	policy.WarnThreshold = calculateWarnThreshold_108(policy.Max, policy.WarnPercent)
	return nil
}

// UpdateUsage_108 updates the usage record with a new current value.
func UpdateUsage_108(usage *PidsUsage_108, current int64) error {
	if usage == nil {
		return ErrUsageNil_108
	}
	if current < 0 {
		return ErrNegativeCurrent_108
	}
	usage.Current = current
	if usage.Max <= 0 {
		usage.Max = DefaultMaxPids_108
	}
	return nil
}

// ============================================================
// Policy Comparison and Merging
// ============================================================

// MergePolicies_108 merges two policies, taking the more restrictive of each field.
func MergePolicies_108(p1, p2 *PidsMaxPolicy_108) *PidsMaxPolicy_108 {
	if p1 == nil && p2 == nil {
		return DefaultPolicy_108()
	}
	if p1 == nil {
		return p2
	}
	if p2 == nil {
		return p1
	}
	merged := &PidsMaxPolicy_108{}
	if p1.Max < p2.Max {
		merged.Max = p1.Max
	} else {
		merged.Max = p2.Max
	}
	if p1.WarnPercent < p2.WarnPercent {
		merged.WarnPercent = p1.WarnPercent
	} else {
		merged.WarnPercent = p2.WarnPercent
	}
	merged.WarnThreshold = calculateWarnThreshold_108(merged.Max, merged.WarnPercent)
	merged.PolicyName = fmt.Sprintf("merged(%s,%s)", p1.PolicyName, p2.PolicyName)
	merged.EnableWarnings = p1.EnableWarnings && p2.EnableWarnings
	return merged
}

// ComparePolicies_108 compares two policies for equality.
func ComparePolicies_108(a, b *PidsMaxPolicy_108) bool {
	if a == nil || b == nil {
		return a == b
	}
	return a.Max == b.Max &&
		a.WarnPercent == b.WarnPercent &&
		a.PolicyName == b.PolicyName &&
		a.EnableWarnings == b.EnableWarnings
}

// ============================================================
// Additional Helpers
// ============================================================

// GetRecommendedAction_108 returns the recommended action for a given warning level.
func GetRecommendedAction_108(level WarningLevel_108) string {
	for _, entry := range DefaultThresholdTable_108 {
		if entry.Level == level {
			return entry.Action
		}
	}
	return "Unknown level"
}

// GetThresholdForPercent_108 returns the threshold entry for a given percent.
func GetThresholdForPercent_108(percent float64) *ThresholdEntry_108 {
	for _, entry := range DefaultThresholdTable_108 {
		if percent >= float64(entry.MinPercent) && percent < float64(entry.MaxPercent) {
			return &entry
		}
	}
	return nil
}

// SortThresholdTable_108 sorts the table by MinPercent ascending.
func SortThresholdTable_108(table []ThresholdEntry_108) {
	sort.Slice(table, func(i, j int) bool {
		return table[i].MinPercent < table[j].MinPercent
	})
}

// GenerateWarningMessage_108 creates a formatted warning message.
func GenerateWarningMessage_108(level WarningLevel_108, current, max int64, policyName string) string {
	percent := ComputeUsagePercent_108(current, max)
	return fmt.Sprintf("[%s] %s: PIDs usage at %s (current=%d, max=%d, policy=%s)",
		level.String_108(), GetRecommendedAction_108(level), FormatUsagePercent_108(percent), current, max, policyName)
}

// DetermineWarningLevelFromPolicy_108 returns the warning level based on the policy threshold.
func DetermineWarningLevelFromPolicy_108(policy *PidsMaxPolicy_108, usage *PidsUsage_108) WarningLevel_108 {
	if !policy.EnableWarnings {
		return WarningNone_108
	}
	percent := ComputeUsagePercent_108(usage.Current, usage.Max)
	if percent >= float64(policy.WarnPercent) {
		// Use threshold table to get severity
		return GetWarningLevel_108(percent, DefaultThresholdTable_108)
	}
	return WarningNone_108
}

// ============================================================
// Policy Validation Suite
// ============================================================

// ValidatePolicyConsistency_108 performs multiple checks and returns a list of errors.
func ValidatePolicyConsistency_108(policy *PidsMaxPolicy_108) []error {
	var errs []error
	if policy == nil {
		return append(errs, ErrPolicyNil_108)
	}
	if err := ValidatePidsMax_108(policy.Max); err != nil {
		errs = append(errs, err)
	}
	if policy.WarnPercent < MinWarnPercent_108 || policy.WarnPercent > MaxWarnPercent_108 {
		errs = append(errs, ErrInvalidWarnPercent_108)
	}
	computedThreshold := calculateWarnThreshold_108(policy.Max, policy.WarnPercent)
	if policy.WarnThreshold != computedThreshold {
		errs = append(errs, fmt.Errorf("warn threshold mismatch: stored %d, computed %d", policy.WarnThreshold, computedThreshold))
	}
	if policy.PolicyName == "" {
		errs = append(errs, errors.New("policy name should not be empty"))
	}
	return errs
}

// ValidatePolicyAgainstHardLimit_108 checks that policy values are within system limits.
func ValidatePolicyAgainstHardLimit_108(policy *PidsMaxPolicy_108) error {
	if policy.Max > HardMaxPids_108 {
		return ErrExceedsHardLimit_108
	}
	return nil
}

// ============================================================
// Metrics and Statistics
// ============================================================

// CalculateWarningStatistics_108 computes simple statistics over a slice of usage.
func CalculateWarningStatistics_108(usages []*PidsUsage_108) (avgPercent float64, maxPercent float64, warningCount int) {
	if len(usages) == 0 {
		return 0, 0, 0
	}
	totalPercent := 0.0
	maxPercent = 0.0
	warningCount = 0
	for _, u := range usages {
		p := ComputeUsagePercent_108(u.Current, u.Max)
		totalPercent += p
		if p > maxPercent {
			maxPercent = p
		}
		if p >= float64(DefaultWarnPercent_108) {
			warningCount++
		}
	}
	avgPercent = totalPercent / float64(len(usages))
	return avgPercent, maxPercent, warningCount
}

// ============================================================
// Safe Wrapper (for nil safety)
// ============================================================

// SafeGetWarnThreshold_108 returns the warn threshold or 0 if policy is nil.
func SafeGetWarnThreshold_108(policy *PidsMaxPolicy_108) int64 {
	if policy == nil {
		return 0
	}
	return policy.WarnThreshold
}

// SafeGetMax_108 returns max or default if policy nil.
func SafeGetMax_108(policy *PidsMaxPolicy_108) int64 {
	if policy == nil {
		return DefaultMaxPids_108
	}
	return policy.Max
}

// SafeGetWarnPercent_108 returns warn percent or default if policy nil.
func SafeGetWarnPercent_108(policy *PidsMaxPolicy_108) int {
	if policy == nil {
		return DefaultWarnPercent_108
	}
	return policy.WarnPercent
}

// ============================================================
// Additional Threshold Table Manipulation
// ============================================================

// AddThresholdEntry_108 adds a new entry to the table, validating and sorting.
func AddThresholdEntry_108(table []ThresholdEntry_108, entry ThresholdEntry_108) ([]ThresholdEntry_108, error) {
	// Check for overlap
	for _, e := range table {
		if e.MinPercent < entry.MaxPercent && entry.MinPercent < e.MaxPercent {
			return nil, fmt.Errorf("overlap with existing entry [%d,%d)", e.MinPercent, e.MaxPercent)
		}
	}
	table = append(table, entry)
	SortThresholdTable_108(table)
	return table, nil
}

// RemoveThresholdEntry_108 removes entries matching a given level.
func RemoveThresholdEntry_108(table []ThresholdEntry_108, level WarningLevel_108) []ThresholdEntry_108 {
	var result []ThresholdEntry_108
	for _, e := range table {
		if e.Level != level {
			result = append(result, e)
		}
	}
	return result
}

// ============================================================
// Policy Copy and Cloning
// ============================================================

// CopyPolicy_108 creates a deep copy of a policy.
func CopyPolicy_108(policy *PidsMaxPolicy_108) *PidsMaxPolicy_108 {
	if policy == nil {
		return nil
	}
	return &PidsMaxPolicy_108{
		Max:            policy.Max,
		WarnPercent:    policy.WarnPercent,
		WarnThreshold:  policy.WarnThreshold,
		PolicyName:     policy.PolicyName,
		EnableWarnings: policy.EnableWarnings,
	}
}

// ============================================================
// String Formatting
// ============================================================

// PolicyString_108 returns a formatted string representation of the policy.
func PolicyString_108(policy *PidsMaxPolicy_108) string {
	if policy == nil {
		return "nil"
	}
	return fmt.Sprintf("PidsMaxPolicy{name=%s, max=%s, warnPct=%d, warnThresh=%d, enabled=%v}",
		policy.PolicyName, FormatPidsMax_108(policy.Max), policy.WarnPercent, policy.WarnThreshold, policy.EnableWarnings)
}

// UsageString_108 returns a formatted string of usage.
func UsageString_108(usage *PidsUsage_108) string {
	if usage == nil {
		return "nil"
	}
	return fmt.Sprintf("PidsUsage{current=%d, max=%s, timestamp=%d}",
		usage.Current, FormatPidsMax_108(usage.Max), usage.Timestamp)
}

// ============================================================
// Initialize and Validate Default Table
// ============================================================

func init() {
	if err := ValidateThresholdTable_108(DefaultThresholdTable_108); err != nil {
		panic("DefaultThresholdTable_108 is invalid: " + err.Error())
	}
}

// EnsureTableValid_108 re-validates the default table (public wrapper).
func EnsureTableValid_108() error {
	return ValidateThresholdTable_108(DefaultThresholdTable_108)
}

// ============================================================
// End of file
// ============================================================
